### ISSUE TITLE
Assistance with creation 

### ISSUE THREAD

**Issue by Enoch310** [aws-samples/sync-agent-presence-with-ms-teams#2]
Hello Michael, 
Thanks for the pretty comprehensive guide. We were able to follow all the steps and create the resources. However, when testing, the sync itself did not happen. What would be the common causes for this? What would we need to check?

**Comment by michaelgoligorsky** [comment]
Check API documentation https://learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-1.0, and make sure you passing correct parameters. Check MS Teams status in the browser by refreshing the page. If user login to MS team from multiple devices it could cause availability override.
