### ISSUE TITLE
get user by display Name from teams side

### ISSUE THREAD

**Issue by azConnectaz** [aws-samples/sync-agent-presence-with-ms-teams#3]
Hey Team , I want to match user by their display name instead of email address . Can You Please tell what changes needs to be done in lambda_function.py o365_get_user_by_email function. It will be very helpful

**Comment by michaelgoligorsky** [comment]
You can create cross-ref table and match agent based on your needs https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http
